name: Check merged true

on:
  pull_request:
    types: [closed]
    branches:
      - release
jobs:
  job-1:
    if: github.event.pull_request. == 'develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run command
      run: echo 'running'
