name: Check merged true

on:
  pull_request:
    types: [closed]
    branches:
      - release
jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      HEAD: ${{ github.event.pull_request.head }}
      BASE: ${{ github.event.pull_request.base }}
    steps:
    - uses: actions/checkout@v2
    - name: run command
      run: |
        echo "HEAD: $HEAD"
        echo "BASE: $BASE"
